# -*- coding: utf-8 -*-
"""plant diseaseclassifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sWaURdSwEu08JrbvKuXxtYYrxPJBmdep
"""

import tensorflow as tf
from tensorflow.keras import models,layers
import matplotlib.pyplot as plt
print("success")

!unzip PlantVillage.zip

image_size=256
batch_size=32
channels=3
epochs=50
dataset=tf.keras.preprocessing.image_dataset_from_directory("PlantVillage",shuffle=True,image_size=(image_size,image_size),batch_size=batch_size)

class_names=dataset.class_names
class_names

for image_batch,label_batch in dataset.take(1):
  for i in  range(12):
    plt.subplot(3,4,i+1)
    print(image_batch[0].shape)
    print(label_batch.numpy())
    plt.imshow(image_batch[i].numpy().astype("uint8"))

from sklearn.model_selection import train_test_split
train_size=0.8
train_ds=dataset.take(54)
train_ds

test_ds=dataset.skip(54)
len(test_ds)

val_size=0.1
len(dataset)*val_size

val_ds=test_ds.take(6)
len(val_ds)

test_ds=test_ds.skip(6)
len(test_ds)

def get_dataset_paritions_tf(ds,train_Split=0.8,val_splits=0.1,test_split=0.1,shuffle=True,shuffle_size=10000):
  ds_size=len(ds)
  if shuffle:
    ds=ds.shuffle(shuffle_size,seed=12)



    train_size=int(train_Split*ds_size)
    val_size=int(val_splits * ds_size)
    train_ds=ds.take(train_size)
    val_ds=ds.skip(train_size).take(val_size)
    test_ds=ds.skip(train_size).take(val_size)
  return train_ds,val_ds,test_ds

train_ds,val_ds,test_ds=get_dataset_paritions_tf(dataset)

train_ds=train_ds.cache().shuffle(1000).prefetch(buffer_size=tf.data.AUTOTUNE)
val_ds=val_ds.cache().shuffle(1000).prefetch(buffer_size=tf.data.AUTOTUNE)
test_ds=test_ds.cache().shuffle(1000).prefetch(buffer_size=tf.data.AUTOTUNE)

resize_and_rescale = tf.keras.Sequential([
  layers.Resizing(image_size,image_size),
  layers.Rescaling(1.0/255)
])

data_agumentation=tf.keras.Sequential([layers.RandomFlip("horizontal_and_vertical"),
                                       layers.RandomRotation(0.2)])

input_shape=(batch_size,image_size,image_size,
channels)
n_classes=3
model=models.Sequential( [resize_and_rescale,
                         data_agumentation,
                         layers.Conv2D(32,(3,3),activation="relu",input_shape=input_shape),
                         layers.MaxPooling2D(2,2),
                         layers.Conv2D(64,(3,3),activation="relu"),
                         layers.MaxPooling2D(2,2),
                         layers.Conv2D(64,(3,3),activation="relu"),
                         layers.MaxPooling2D(2,2),
                         layers.Conv2D(64,(3,3),activation="relu"),
                         layers.MaxPooling2D(2,2),
                         layers.Conv2D(64,(3,3),activation="relu"),
                         layers.MaxPooling2D(2,2),
                         layers.Conv2D(64,(3,3),activation="relu"),
                         layers.MaxPooling2D(2,2),
                          layers.Flatten(),
                          layers.Dense(64,activation="relu"),
                          layers.Dense(n_classes,activation="softmax")





















                         ])
model.build(input_shape=input_shape)
model.summary()

model.compile(optimizer="adam",loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),metrics=['accuracy'])

history=model.fit(train_ds,epochs=epochs,batch_size=batch_size,verbose=1,validation_data=val_ds)

model.evaluate(test_ds)

history

history.params
history.history.keys()
type(history.history['loss'])

len(history.history['loss'])

history.history['loss'][:5] # show loss for first 5 epochs

acc = history.history['accuracy']
val_acc = history.history['val_accuracy']

loss = history.history['loss']
val_loss = history.history['val_loss']

plt.figure(figsize=(8, 8))
plt.subplot(1, 2, 1)
plt.plot(range(epochs), acc, label='Training Accuracy')
plt.plot(range(epochs), val_acc, label='Validation Accuracy')
plt.legend(loc='lower right')
plt.title('Training and Validation Accuracy')

plt.subplot(1, 2, 2)
plt.plot(range(epochs), loss, label='Training Loss')
plt.plot(range(epochs), val_loss, label='Validation Loss')
plt.legend(loc='upper right')
plt.title('Training and Validation Loss')
plt.show()

import numpy as np
for images_batch, labels_batch in test_ds.take(1):

    first_image = images_batch[0].numpy().astype('uint8')
    first_label = labels_batch[0].numpy()

    print("first image to predict")
    plt.imshow(first_image)
    print("actual label:",class_names[first_label])

    batch_prediction = model.predict(images_batch)
    print("predicted label:",class_names[np.argmax(batch_prediction[0])])

from matplotlib import image
def predict(model, img):

    img_array = tf.keras.preprocessing.image.img_to_array(img)

    img_array = tf.expand_dims(img_array, 0)


    predictions = model.predict(img_array)


    predicted_class = class_names[np.argmax(predictions[0])]

    confidence = round(100 * (np.max(predictions[0])), 2)

    return predicted_class, confidence

plt.figure(figsize=(15,15))

for images, labels in test_ds.take(1):
    for i in range(9):
        ax = plt.subplot(3, 3, i + 1)
        # We pass the actual numpy array to the fixed predict function
        img_data = images[i].numpy()
        plt.imshow(img_data.astype("uint8"))

        predicted_class, confidence = predict(model, img_data)

        actual_class = class_names[labels[i]]
        plt.title(f"Actual: {actual_class}\nPred: {predicted_class} ({confidence}%)")
        plt.axis("off")

from google.colab import drive
drive.mount('/content/drive')

import os
save_path = '/content/drive/MyDrive/plant_disease_classifier'
if not os.path.exists(save_path):
    os.makedirs(save_path)

# Saving as a .h5 file or a SavedModel folder
model.save(f'{save_path}/plant_model.h5')
print("Model saved to Google Drive!")

model.save('plant_model.h5')

from google.colab import files
files.download('plant_model.h5')

!pip install fastapi uvicorn pyngrok nest_asyncio python-multipart

import tensorflow as tf

# 1. Load the actual file I see in your sidebar
Model = tf.keras.models.load_model('plant_model.h5')

# 2. Make sure your class names are defined here too!
# Replace these with your actual 3 labels (e.g., Potato_Blight, etc.)
class_names = ['Early Blight', 'Late Blight', 'Healthy']

print("✅ Model is now loaded into memory!")

import nest_asyncio
import uvicorn
from fastapi import FastAPI, File, UploadFile
import numpy as np
from io import BytesIO
from PIL import Image
import tensorflow as tf
import threading

# 1. Fix the Colab asyncio loop issue
nest_asyncio.apply()

app = FastAPI()

# --- PREDICTION LOGIC FUNCTIONS ---

def read_file_as_image(data) -> np.ndarray:
    """Converts uploaded bytes into a resized numpy array for the model."""
    image = Image.open(BytesIO(data)).convert("RGB").resize((256, 256))
    return np.array(image)

@app.post("/predict")
async def predict(file: UploadFile = File(...)):
    # A. Read the incoming file
    image = read_file_as_image(await file.read())

    # B. Preprocess: Scale (0-1) and add Batch Dimension (1, 256, 256, 3)
    # Note: Make sure your training used 1/255 rescaling!
    img_batch = np.expand_dims(image, 0)

    # C. Prediction using the 'model' variable from your previous cells
    predictions = Model.predict(img_batch)

    # D. Get results using your 'class_names' list
    predicted_class = class_names[np.argmax(predictions[0])]
    confidence = np.max(predictions[0])

    return {
        "class": predicted_class,
        "confidence": float(round(confidence * 100, 2))
    }

@app.get("/ping")
async def ping():
    return {"status": "Plant Classifier API is Online"}

# --- THE BACKGROUND SERVER FIX ---

def run_api():
    # Use 0.0.0.0 so the tunnel can find the server
    config = uvicorn.Config(app, host="0.0.0.0", port=8000, log_level="info")
    server = uvicorn.Server(config)
    server.run()

# This starts the server without blocking your notebook
if 'api_thread' not in globals() or not api_thread.is_alive():
    api_thread = threading.Thread(target=run_api)
    api_thread.start()
    print("✅ FastAPI is now running in the background on port 8000!")
else:
    print("⚠️ API is already running. To update code, restart the session.")

# 1. Install localtunnel if you haven't already
!npm install -g localtunnel

# 2. Get your "Password" IP (this is required to unlock the link)
import urllib
print("Your Tunnel Password (IP) is:", urllib.request.urlopen('https://ipv4.icanhazip.com').read().decode('utf8').strip())

# 3. Start the tunnel to Port 8000
!lt --port 8000